# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-23 12:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='locality_mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality_key', models.CharField(max_length=400)),
                ('tahsil', models.CharField(max_length=400)),
                ('district', models.CharField(max_length=400)),
                ('state', models.CharField(max_length=400)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=7)),
                ('marital_status', models.CharField(max_length=15)),
                ('profession', models.CharField(max_length=100)),
                ('education_key', models.CharField(max_length=40)),
                ('education_details', models.TextField()),
                ('address_key', models.CharField(max_length=50)),
                ('alive_flag', models.BooleanField()),
                ('father_id', models.IntegerField()),
                ('mother_id', models.IntegerField()),
                ('profile_pic', models.ImageField(blank=True, default='media/images/profiles/default.png', upload_to='media/images/profiles/')),
                ('life_partner_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
