# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmbassadorPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locality_mapping',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'managed': False},
        ),
    ]
