# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmbassadorPortal', '0003_auto_20190426_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locality_mapping',
            options={},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={},
        ),
    ]
