# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmbassadorPortal', '0004_auto_20190426_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='address_key',
        ),
        migrations.AddField(
            model_name='people',
            name='locality_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AmbassadorPortal.locality_mapping'),
        ),
        migrations.AddField(
            model_name='people',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='locality_mapping',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='people',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
