# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-29 10:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AmbassadorPortal', '0005_auto_20190426_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='news_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('news_date', models.DateField()),
                ('news_title', models.CharField(max_length=400)),
                ('news_description', models.TextField()),
                ('news_category', models.CharField(max_length=400)),
                ('new_attachment', models.ImageField(blank=True, upload_to='BeingMomin/media/images/news_attachment/')),
                ('verified', models.BooleanField()),
                ('currently_show', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locality', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AmbassadorPortal.locality_mapping')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        )
    ]
